/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gotit_quyle_dnn_dm3_NativeClass */

#ifndef _Included_com_gotit_quyle_dnn_dm3_NativeClass
#define _Included_com_gotit_quyle_dnn_dm3_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gotit_quyle_dnn_dm3_NativeClass
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gotit_quyle_dnn_1dm3_NativeClass_getStringFromNative__
  (JNIEnv *, jclass);

/*
 * Class:     com_gotit_quyle_dnn_dm3_NativeClass
 * Method:    getStringFromNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gotit_quyle_dnn_1dm3_NativeClass_getStringFromNative__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_gotit_quyle_dnn_dm3_NativeClass
 * Method:    findFeatures
 * Signature: (II[B[I)V
 */
JNIEXPORT void JNICALL Java_com_gotit_quyle_dnn_1dm3_NativeClass_findFeatures
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_gotit_quyle_dnn_dm3_NativeClass
 * Method:    readNet
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gotit_quyle_dnn_1dm3_NativeClass_readNet
  (JNIEnv *, jclass);

/*
 * Class:     com_gotit_quyle_dnn_dm3_NativeClass
 * Method:    imageProcessing
 * Signature: (II[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_gotit_quyle_dnn_1dm3_NativeClass_imageProcessing
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
